### ISSUE TITLE
Peer Review - Milestone 1

### ISSUE THREAD

**Issue by PulkitMathur** [airavata-courses/Rangers#10]
For MySQL installation, a standalone MySQL server is required or Sandbox InnoDB Cluster? Also do we need to configure a specific port for this?

**Comment by PulkitMathur** [comment]
Also could you please clarify how to create the databases and tables and using which specific MySQL tool?

**Comment by ameyarangal** [comment]
> Also could you please clarify how to create the databases and tables and using which specific MySQL tool?

There are detailed steps mentioned in the 'Setup and Installation' page in Wiki for setting up the database. Please let us know if you still need any assistance.

**Comment by cbrahme** [comment]
I have included MySQL installation steps in Wiki. 

[ Note : 
Install a standalone MySQL server.  And you can keep the default settings while installing, including port number. ]

Please let me know if you still need any help.

**Comment by PulkitMathur** [comment]
It would be better if you could provide a dump file or a script which directly creates all the databases and tables. Another way is to add screenshots to the installation page related to how to create the database/tables.
