### ISSUE TITLE
Error Installing smtplib

### ISSUE THREAD

**Issue by PulkitMathur** [airavata-courses/Rangers#11]
Got error installing smtplib "Could not find a version that satisfies the requirement smtplib (from versions: )
No matching distribution found for smtplib"

**Comment by rohankasture** [comment]
smtplib is a built-in package for both python2.7 and python3.x, so there is no need for installation. You can import it without installing any other package.
I updated the wiki. It was a miss on my part. "pip install smtplib" is not required.

**Comment by aralshi** [comment]
You can create a requirements file so that it can be used to install all the dependencies required for your flask service.

**Comment by rohankasture** [comment]
I have created the requirements file which can be used to install all the dependencies.
