### ISSUE TITLE
Milestone1 : Peer Review

### ISSUE THREAD

**Issue by aralshi** [airavata-courses/Rangers#13]
User Service:
Entities are present in models folder and models are present in entity folder. Was there any specific reason for it?

Wiki Suggestion:
1. Include steps in wiki to change password for database in both spring boot and node js service.
2. Can use `spring.jpa.hibernate.ddl-auto=create` property to create new tables rather than manually creating them as given in wiki.
3. Python dependencies can be given in requirements file so that It can be installed together.

**Comment by rohankasture** [comment]
I have added requirements.txt file to ease the installation process

**Comment by cbrahme** [comment]
I have resolved the package structure issue of model and entity for User service.

**Comment by aralshi** [comment]
More Wiki suggestions:
1. For Notification service, Please mention to set content-type of header of the postman request.
2. DDL given to create room table contains unwanted characters. (Copy paste error)

**Comment by aralshi** [comment]
Final Review:
1. I was able to start all the services and front end, create new user and login with those credentials. 
2. I could not see the added listing on view listing page and on adding new listing I got following error.
![image](https://user-images.githubusercontent.com/32557745/52540883-b6e1c000-2d5c-11e9-9150-fe630afb015d.png)
3. I could not understand how notification service is being used in the application right now.

Suggestion:
1. Wiki can be improved to have better documentation of steps needed to start the application.
2. Front end needs to be more user friendly to use.(CSS needs to be done).
3. React application should route itself to /login instead of user manually typing the path.

**Comment by aralshi** [comment]
After pulling latest code for room service, Add listing and view listing is working but booking is not working.

**Comment by rohankasture** [comment]
@aralshi  Please pull the latest changes on UI branch and let me know if you face any issue in booking.

**Comment by aralshi** [comment]
@rohankasture It gives no error now. Thanks!
