### ISSUE TITLE
mysql error in creating table "room"

### ISSUE THREAD

**Issue by maheshbelnekar** [airavata-courses/Rangers#15]
OS: Mac OS
mysql version: mysql  Ver 8.0.14 for macos10.14 on x86_64 (MySQL Community Server - GPL)

* Create room command fails with error : 
> ERROR 1064 (42000): You have an error in your SQL syntax

> Tip: Providing an sql dump is easy and convenient.

Screenshot:
<img width="703" alt="screen shot 2019-02-08 at 6 25 10 pm" src="https://user-images.githubusercontent.com/2353327/52512296-1e1f3900-2bd2-11e9-9e33-eaf9ffbfcfa0.png">

**Comment by ameyarangal** [comment]
Can you please try below command

CREATE TABLE rooms
     (
      id              INT unsigned NOT NULL AUTO_INCREMENT, 
       location            VARCHAR(150) NOT NULL,                
       owneremail           VARCHAR(150) NOT NULL,           
       guests           INT NOT NULL,                        
       available           TINYINT NOT NULL,            
       price           INT NOT NULL,                        
       description           VARCHAR(150) NULL,  
       wifi           TINYINT NOT NULL,                  
       microwave           TINYINT NOT NULL,      
       safeCloset           TINYINT NOT NULL,      
       PRIMARY KEY     (id));

**Comment by maheshbelnekar** [comment]
Thanks @ameyarangal , it worked.
