### ISSUE TITLE
Peer review for Project 1

### ISSUE THREAD

**Issue by maheshbelnekar** [airavata-courses/Rangers#16]
Great concept for the project and even liked the presentation. Following are my observations:

Like the concept of the project but would have been great if all a "develop" or "release" branch was maintained. Absence of which requires me to maintain a separate copy of each branch in order to run all micro 

- Absence of a "develop" or "release" branch causes an issue requiring me to maintain a separate copy of each branch in order to run all micro-processes and even check all commits. Having one single branch would have helped.

- Issue with running mysql query to create "room" table( #15). Here as well, providing an sql dump would have helped. **fixed**

- Missing steps on how to run UserService #17. **fixed**

- Facing same issue as #18. **fixed**

- No guide on how to get started with the application - #19, running the UI service just opens a blank webpage. **fixed**

- CORS policy issue #20 .

**Comment by cbrahme** [comment]
I have updated wiki with the commands to run user service. #17

**Comment by ameyarangal** [comment]
> * Absence of a "develop" or "release" branch causes an issue requiring me to maintain a separate copy of each branch in order to run all micro-processes and even check all commits. Have one single branch would have helped.

I completely agree with you having a dev or release branch, but we can maintain that structure only when we have different repositories. But in this course, we can have only one repo and all the services need to be in separate branches for code separation. Once we configure CI/CD I think your concerns with multiple branches will be resolved as then we just need to trigger one build. Hope this helps, let me know if you still have any concerns.

**Comment by maheshbelnekar** [comment]
Yes that's true that each webservice needs a separate branch for development but Marlin discussed in the lectures, all code needs to be merged back to develop branch and also maintaining a release branch is useful.

Said that, it's the team's choice on what should be followed. If this works better for you then you should go forward with this.

**Comment by maheshbelnekar** [comment]
All issues have been fixed and closed except for #20 . Closing this issue, while keep #20 open.
