### ISSUE TITLE
Error in running UserService

### ISSUE THREAD

**Issue by maheshbelnekar** [airavata-courses/Rangers#17]
### **Note: This might be cause because steps on how to run UserService are not mentioned in the wiki**

I run UserService using follow commands(Please let me know if these are correct):
```
$ git checkout UserService
$ cd userservice/
$ mvn clean install
```
### This gives me below error(Same error for running):
<img width="682" alt="screen shot 2019-02-08 at 8 07 08 pm" src="https://user-images.githubusercontent.com/2353327/52514210-d7cfd700-2bdd-11e9-8269-85455d8964c2.png">

**Comment by cbrahme** [comment]
I tried running the same command on my machine. The application works fine.

Try adding following plugin in pom.xml.

https://stackoverflow.com/questions/36427868/failed-to-execute-goal-org-apache-maven-pluginsmaven-surefire-plugin2-12test 

Let me know if the problem persists.

**Comment by maheshbelnekar** [comment]
Thanks @cbrahme , that issue is resolved now. But I am getting a runtime error. **It looks the access is denied to the mysql database.** I have set the mysql password to 'password' as given in the "Steps to run the Room Notification Service". Is UserService using some other password? Let me know how can I change it.

<img width="682" alt="screen shot 2019-02-09 at 11 50 10 am" src="https://user-images.githubusercontent.com/2353327/52525395-25e4e900-2c77-11e9-9740-32262961c780.png">

**Comment by cbrahme** [comment]
I have resolved the database connection issue and the new code is available on UserService branch.
Please checkout the latest commit and revert back if you face any issues.

**Comment by maheshbelnekar** [comment]
@cbrahme great! I was able to run the service.

About the original issue, where you suggested me to add the "surefire" plugin to my pom.xml, does that needs to be committed to the code? Or was is just specific to my machine, that's why we are not updating the repo?
