### ISSUE TITLE
Error while running UI

### ISSUE THREAD

**Issue by aralshi** [airavata-courses/Rangers#18]
I am getting following error when I tried to run reach server:

![screen shot 2019-02-09 at 9 35 02 pm](https://user-images.githubusercontent.com/32557745/52528705-d02e3200-2cb2-11e9-8c89-11affd53d5f6.png)

**Comment by ameyarangal** [comment]
Issue resolved in [Commit](https://github.com/airavata-courses/Rangers/commit/b868a74f356265badbe739caa1f554aa3fb8175e). Can you please validate and close the issue
