### ISSUE TITLE
Missing steps on how to get started with the application

### ISSUE THREAD

**Issue by maheshbelnekar** [airavata-courses/Rangers#19]
Now that I have setup and got all services to run. I don't know how should I actually start using the system.

The UI service launches **http://localhost:3000/** but that a blank page with no link.
<img width="955" alt="screen shot 2019-02-10 at 2 38 13 pm" src="https://user-images.githubusercontent.com/2353327/52538527-d9b2ab00-2d41-11e9-96ff-ac9046d841b7.png">

**Comment by ameyarangal** [comment]
Sorry, can you please navigate to localhost:3000/login. We have updated getting started section in Wiki. Thanks for the comment.

**Comment by maheshbelnekar** [comment]
Got it! Thanks @ameyarangal.
