### ISSUE TITLE
Booking failed by CORS policy (console error attached)

### ISSUE THREAD

**Issue by maheshbelnekar** [airavata-courses/Rangers#20]
When I try to book an apartment from the listing, CORS policy fails access.

> No error shown on UI.

> Console shows CORS policy error:

<img width="1057" alt="screen shot 2019-02-10 at 5 13 59 pm" src="https://user-images.githubusercontent.com/2353327/52540427-4a17f700-2d57-11e9-959c-465be6f1ed53.png">

**Comment by ameyarangal** [comment]
Can you please validate, we have fixed the issue.  Pull latest UI branch

**Comment by maheshbelnekar** [comment]
Thanks @ameyarangal. Working fine! Closing issue.
