### ISSUE TITLE
Peer Review - Milestone 2

### ISSUE THREAD

**Issue by sairohithA007** [airavata-courses/Rangers#30]
Hi Rangers,

I have gone through your wiki. I'm waiting for your Jenkins credentials. Can you please share the details as soon as possible so that I can review and get back to you.

Thanks,

**Comment by ameyarangal** [comment]
I have send you a mail with credentials, please let me know if anything.

**Comment by sairohithA007** [comment]
Thank you. Will look into it.

**Comment by sairohithA007** [comment]
I was able to login to Jenkins successfully. I have gone through the architecture diagram in the wiki and tried to relate the job present in the Jenkins homepage. I'm not able to find Add room vacancy micro service,  Feedback micro service, search room micro service. Does all these services are present in user service and room service jobs?

**Comment by ameyarangal** [comment]
We have not implemented feedback service. Add and virw listings are in room service

**Comment by sairohithA007** [comment]
Okay got it. I'm planning to perform a commit and check how the application is being deployed. Other peer reviewers or you guys may be playing around with the Jenkins. Can you please provide me a time slot so that I can do this?
I wanted to the release branch as well so that I can perform a dummy commit.

**Comment by sairohithA007** [comment]
I was able to find the branch and IP in the wiki. Please provide a time slot and port for user interface.

**Comment by ameyarangal** [comment]
I think you can do the dummy commit and check the CI/CD. 3000 port is used for UI. For accessing UI hit http://149.165.157.35:3000/login

**Comment by sairohithA007** [comment]
Okay, thank you. Will try to perform commit and check.

**Comment by sairohithA007** [comment]
Notification service is deployed successfully through git commit.

**Comment by sairohithA007** [comment]
Room service is also deployed successfully through git commit.

**Comment by sairohithA007** [comment]
UI is also deployed successfully through git commit, though it has taken time. I was able to access the UI from browser and perform login and registration. Will test other functionalities after deploying the next(last) service.

**Comment by sairohithA007** [comment]
I waiting past 15 minutes for the user service to be deployed. The console output is as follows:
```
Started by GitHub push by sairohithA007
Obtained Jenkinsfile from git https://github.com/airavata-courses/Rangers.git
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Still waiting to schedule task
‘userservice’ is offline
```

**Comment by ameyarangal** [comment]
> I waiting past 15 minutes for the user service to be deployed. The console output is as follows:
> 
> ```
> Started by GitHub push by sairohithA007
> Obtained Jenkinsfile from git https://github.com/airavata-courses/Rangers.git
> Running in Durability level: MAX_SURVIVABILITY
> [Pipeline] Start of Pipeline
> [Pipeline] node
> Still waiting to schedule task
> ‘userservice’ is offline
> ```

Problem is solved and build is successfully deployed. I have rebuild the userservice job, can you please check

**Comment by sairohithA007** [comment]
Thank you. Will try to do a git commit again.

**Comment by sairohithA007** [comment]
This time user service is deployed successfully. Now I will go through the UI and check if everything is working fine.

**Comment by sairohithA007** [comment]
I faced two issues out of which one is #32 is already discovered and the other is #33

**Comment by sairohithA007** [comment]
#33 is fixed.

**Comment by sairohithA007** [comment]
Summary:

The home page wiki was useful to go through the project's use cases using napkin diagram. 
The milestone-2 wiki is very much helpful in understanding the logistics of the application and navigating to Jenkins jobs directly by one click.

The CI/CD process through works fine.
The issue #33  is also fixed.

**Comment by sairohithA007** [comment]
Closing this issue as #32 is also fixed.
