### ISSUE TITLE
Error when running the application

### ISSUE THREAD

**Issue by uteerna** [airavata-courses/Rangers#32]
Hi Team, 

The CI/CD implementation for your project works well. The Jenkins pipeline stages are implemented properly. I also liked that you have used Docker in this milestone. But I am getting an error when I try to run the application. I get the following error in add listing.
![whatsapp image 2019-03-03 at 1 45 52 pm](https://user-images.githubusercontent.com/31369347/53700093-d5b3ff00-3dbc-11e9-8fef-e1a2246634a3.jpeg)

**Comment by cbrahme** [comment]
We have fixed this issue. Please check if you are able to perform the functionalities.

**Comment by uteerna** [comment]
Hi, I am now able to perform the functionality.
