### ISSUE TITLE
I think one of the IP address is not changed.

### ISSUE THREAD

**Issue by sairohithA007** [airavata-courses/Rangers#33]
When I clicked on book button, the application is doing nothing and on the console it says "http://localhost:55555/notify" as connection refused.

<img width="1679" alt="screen shot 2019-03-03 at 5 07 10 pm" src="https://user-images.githubusercontent.com/29268449/53702640-20427500-3dd7-11e9-878e-348efb83083d.png">

**Comment by rohankasture** [comment]
We have changed the IP address. Could you please test it again and revert back if you face any issue

**Comment by sairohithA007** [comment]
Tested it and everything went well. I got an email regarding my booking.

**Comment by sairohithA007** [comment]
Closing the issue as it is fixed.
