### ISSUE TITLE
clicking on notification branch takes me to 404 page

### ISSUE THREAD

**Issue by AdithyaHS** [airavata-courses/Rangers#35]
![screenshot from 2019-03-03 20-43-35](https://user-images.githubusercontent.com/43458852/53705862-67d7f980-3df5-11e9-92d8-bc1dd1f32a90.png)

**Comment by ameyarangal** [comment]
Are you still facing the same issue? I am not able to reproduce this.

**Comment by AdithyaHS** [comment]
Hello @ameyarangal ,

No, I am not facing this issue anymore. I will be closing this issue now, Thanks.
