### ISSUE TITLE
Peer Review - Milestone 3

### ISSUE THREAD

**Issue by vanessapinto257** [airavata-courses/Rangers#41]
Hey team, could you give me the link where I can access the project? I can't seem to find it on the Milestone 3 wiki.

**Comment by rohankasture** [comment]
I have mailed you the credentials and updated the wiki

**Comment by vanessapinto257** [comment]
Thanks!

When I try to register on the website, no action takes place. Could you take a look into it?

**Comment by vanessapinto257** [comment]
Kubernetes is working well and so is the fault tolerance!
The UI could be improved however!
