### ISSUE TITLE
Peer review - Milestone 4

### ISSUE THREAD

**Issue by chetan253** [airavata-courses/Rangers#47]
Hi Team,

I've reviewed the system and made the following observations: 
* Jenkins is properly deploying on both deployments
* Blue-Green deployments are working great
* I was able to log in properly via Google OAuth and use functionality
* Wiki needs to be updated in case of diagram and information for Open ID

Thanks,
Chetan

**Comment by rohankasture** [comment]
We have updated the wiki with information on Open ID and updated the architecture diagram with respect to the latest milestone.

**Comment by chetan253** [comment]
Looks great!!
