### ISSUE TITLE
Peer Review 4

### ISSUE THREAD

**Issue by deepakh2810** [airavata-courses/Rangers#48]
Hi Team,

Having reviewed the wiki and the Application, i have the following points:

Jenkins is properly deploying on both deployments.
I was able to log in properly via Google OAuth and use functionality.
Blue-Green deployments are working great.

Suggestion:

Although the functionality is working as expected, i would suggest to make improvements on the UI, going forward.

Best,
Deepak H

**Comment by rohankasture** [comment]
Thanks. We are working on UI and would be presenting the updated UI tomorrow.
