### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by kulsv** [airavata-courses/Rangers#49]
Hi Team,
Here are some of the issues I faced while trying to review the application:
1. Logout functionality is not working and taking too long. Ends up with timeout error.
2. After signing up and logging into the application using traditional way, I could see the password printed in the console in plain text. Is hashing/encoding of password implemented in the backend?

A small suggestion:
Sometimes, images and data do not get loaded on the home screen. Trying to refresh the page redirects to the login page which I think should not be the case. Refreshing the page should be allowed/handled.

Otherwise,
OAuth is working fine. Other functionalities are perfectly fine as well.

Please let me know if I understood any of the points wrongly.

Thanks,
Shweta

**Comment by rohankasture** [comment]
The logout issue or any particular page taking too long is related to IU or TACC servers and is something beyond our control. I also faced a similar issue. We have not implemented hashing/encryption of password in the backend as there were other things which we thought are more important and needed prior attention. But yes we should ideally hash the password for security reasons.

**Comment by kulsv** [comment]
Rest all looks good. Closing this issue.
